services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: soop
      POSTGRES_PASSWORD: gumanoid99
      POSTGRES_DB: projectfsp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U soop -d projectfsp"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_ENV: development
      DATABASE_URL: postgresql+asyncpg://soop:gumanoid99@db:5432/projectfsp
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head && python main.py"

volumes:
  postgres_data: